// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zzhymiyrrppytyzavprl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp6aHltaXlycnBweXR5emF2cHJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NTIxNTQsImV4cCI6MjA2MzQyODE1NH0.bBYQ1-g9cSz8L-du8HtUo7J-pR84YrqnflCd_6ECXwE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);